Subject: Unable to read my mail for a few days
MIME-Version: 1.0
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 7BIT

Regarding your email with subject:
	$SUBJECT

I will be unable to read my mail for a while, since I'm on vacation.
Your message has been saved and I will read and respond to it when I
return.  You should receive only one copy of this automatic reply, no
matter how much mail you send.
