#!/bin/sh -
#
# This script should be run periodically by cron to resubmit messages that
# the router hasn't been able to deal with (e.g. sender envelope address
# resolution was deferred).
#
. /etc/zmailer.conf
cd $POSTOFFICE/deferred || exit 1
exec find . -type f -name '[0-9]*' -exec mv '{}' ../router \;
