#! /bin/bash
output=docbook2html-dir
skip=0
for arg in $*
do
  #a=$arg
  if [ $skip -gt 1 ]
  then
    skip=$(($skip - 1))
    continue
  fi
  case $arg in
  -h|--help|-v|--version)	break
				;;
  -n|--nostd|-u|--nochunks|-html-index)	skip=1
				;;
  -*)				skip=2
				;;
  *)	output="$(echo $arg | sed 's,\.sgml$,,;s,\.sgm$,,')"
	break
	;;
  esac
done
if [ -d ${output} ]
then
  rm -rf ${output}.junk
  mv ${output} ${output}.junk
fi
mkdir ${output}
jw -f docbook -b html -o ${output} $*
